### ISSUE TITLE
Question about the paper + plan to provide the score information

### ISSUE THREAD

**Issue by Jasonlee1995** [pratyushmaini/ssft#1]
<img width="700" alt="image" src="https://github.com/pratyushmaini/ssft/assets/49643709/c3380297-cb6c-41cb-a703-8eb34276d245">
<img width="700" alt="image" src="https://github.com/pratyushmaini/ssft/assets/49643709/64cb81b8-c8fb-4d74-95ff-1450f8e2a789">

Hi.

I recently read your paper and just curious about the `Figure 6` on the Appendix.

In `Figure 1`, there are no such data with (low fslt, low ssft)

But there are (low fslt, low ssft) data in `Figure 6`.

What characteristic of (low fslt, low ssft) data is?

Are these data can be classfied by simplicity-bias feature but actually hard data?

I cannot imagine the characteristic of the (low fslt, low ssft) data.

Also, is there plan to provide the score information of the dataset?
(csv or json file of fslt, ssft information of CIFAR-10, ...)

**Comment by pratyushmaini** [comment]
Hi Jason! 
Thanks for your interest. I have provided SSFT masks for CIFAR 10 here (https://github.com/pratyushmaini/ssft/tree/main/masks/cifar10) Let me know if this is helpful for you. We discuss the concept of Ambiguous examples in Figure 2 (b) which is similar to the bottom left quadrant in Figure 6. But in general, we find that such examples were learned early because of a particular initialization of the network, but are forgotten early because of being ambiguous. However, we so not have a strong hypothesis about the same (like other theoretical results)

**Comment by Jasonlee1995** [comment]
Thanks for the reply and I have another questions.

1. Averaging the (fslt, ssft)

You said that those ambiguous samples `were learned early because of a particular initialization of the network`.

Then, just averaging the (fslt, ssft) with many independent runs can solve those issues?


2. Difference between other measures?

<img width="600" alt="image" src="https://github.com/pratyushmaini/ssft/assets/49643709/f53e1636-05b1-4a0e-9ea9-c8564edc472c">
<img width="500" alt="image" src="https://github.com/pratyushmaini/ssft/assets/49643709/79e53b1f-b6a0-430d-8376-237c42006b08">

It looks ambiguous and atypical looks challenging for human also.

Paper you mentioned (Characterizing Structural Regularities of Labeled Data in Overparameterized Models) also classify 3 types of hard examples.
(of course, they do not characterize each type as their example difficulty score)

For C-score, the learning of ambiguous, atypical, mislabeled are quite late, but your fslt shows that ambiguous learns early.

Concept of C-score and fslt looks highly similar, but why the difference occur?

**Comment by pratyushmaini** [comment]
Regarding (1):
Can averaging multiple runs solve this issue: We do observe that the density of samples in the third quadrant reduces significantly as we average over multiple runs. In fact, in some of my experiments on averaging between runs of different architectures, I saw that this region becomes even less dense. So I would guess that some architectures have a natural bias to classify some ambiguous samples correctly early on in training, independent of the initialization. Again, these are just preliminary observations I had when I was doing these experiments, and may not be statistically consistent, so take them with a word of caution.

Regarding (2):
C-score is very similar to FSLT, then why this difference: I agree with your point. And you can understand this based on the same reasoning as above---to calculate C-score multiple random runs of the model are averaged together. This is very expensive but helps alleviate the randomness because of the initialization.

I hope these answer your questions!
